export const POSTS_GET_ALL = 'POSTS_GET_ALL';
export const POSTS_UPDATE = 'POSTS_GET_BY_USER';
export const POSTS_LOADING = 'POSTS_LOADING';
export const POSTS_ERROR = 'POSTS_ERROR';
export const POSTS_COMMENTS_UPDATE = 'POSTS_COMMENTS_GET_BY_USER';
export const POSTS_COMMENTS_LOADING = 'POSTS_COMMENTS_LOADING';
export const POSTS_COMMENTS_ERROR = 'POSTS_COMMENTS_ERROR';
